analytics.account={"id"\:1676125,"name"\:"My Account_01","uuid"\:"a5095943-aea2-438c-b75d-8096bc010877","domain"\:"ac-1676125"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization=null
analytics.onpremise.server=https\://testops.katalon.io
analytics.project={"id"\:3473395,"name"\:"DATN_22010181_Katalon_Phenikaa","teamId"\:3459173,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3490006,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3459173,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
onpremise.email=22010181@st.phenikaa-uni.edu.vn
onpremise.password=1J4CsYMQz1mpspZ8EgN84mheHoy1/uc2msVmYfpFnt5Inu1tl10/5A\=\=
